---

- name: Include distribution variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
  tags: [ 'always' ]

- name: Enable OSC repository
  yum:
    name: "{{ osc_release_rpm }}"
    state: present
    disable_gpg_check: "{{ osc_gpg_check | bool }}"

- name: Enable TurboVNC repository
  ansible.builtin.yum_repository:
    name: turbovnc
    state: present
    baseurl: "{{ turbovnc_repo }}"
    gpgkey:
      - https://packagecloud.io/dcommander/turbovnc/gpgkey
      - https://raw.githubusercontent.com/TurboVNC/repo/main/VGL-GPG-KEY
      - https://raw.githubusercontent.com/TurboVNC/repo/main/VGL-GPG-KEY-1024
    gpgcheck: true
    description: "TigerVNC repository"
  when: turbovnc_repo | default('') | length > 0

- name: Install ood rpms for vnc
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ ood_vnc_rpms }}"

- name: Create websocify ood default path
  file:
    path: "/opt/websockify"
    state: directory
    mode: 0755

- name: Symlink websocify ood default bin for simplicity
  file:
    src: "/usr/bin/websockify"
    path: "/opt/websockify/run"
    state: link

- name: Make udev permission correct for DRI card
  copy:
    dest: /etc/udev/rules.d/50-card.rules
    owner: root
    group: root
    mode: 0644
    content: 'KERNEL=="card*", NAME="dri/card%n", MODE="0666"'

- name: Install Xfce when enabled
  yum:
    name: "@Xfce"
    state: present
  when: install_xfce

- name: Install extra X packages
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ xfce_extra_rpms }}"
  when: install_xfce

- name: Revert systemd back to console if installed Xfce
  file:
    src: /usr/lib/systemd/system/multi-user.target
    dest: /etc/systemd/system/default.target
    state: link
  when: install_xfce

- name: Copy maximizer plugin for Xfce when enabled
  copy:
    src: "xfce/{{ item }}"
    dest: "/usr/lib64/xfce4/panel/plugins/{{ item }}"
    mode: 0644
    owner: root
    group: root
  when: install_xfce
  with_items:
    - libmaximus.la
    - libmaximus.so

- name: Copy maximizer plugin conf for Xfce when enabled
  copy:
    src: "xfce/maximus.desktop"
    dest: /usr/share/xfce4/panel/plugins
    mode: 0644
    owner: root
    group: root
  when: install_xfce

- name: Disabling notification on the unregistered systems
  ansible.builtin.lineinfile:
    dest: "{{ item }}"
    regexp: '^(?i)(ExecStart=/usr/libexec/gsd-subman.*)'
    replace: '# \1'
    backrefs: yes
    state: present
  loop:
    - /lib/systemd/user/org.gnome.SettingsDaemon.Subscription.service
    - /etc/xdg/autostart/org.gnome.SettingsDaemon.Subscription.desktop
  when: disable_unregistered_not is defined
