---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: rockylinux/rockylinux:9-ubi
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        install_xfce: true
verifier:
  name: ansible
